apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: netby-inventory
type: Opaque
stringData:
  SA_PASSWORD: "StrongP@ssw0rd123!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: netby-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
          - name: mssql-storage
            mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: netby-inventory
spec:
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: netby-inventory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi